export const CONTRACT_INSTANCE = "CONTRACT_INSTANCE";
export const CURRENT_ACCOUNT = "CURRENT_ACCOUNT";
export const METAMASK_STATUS = "METAMASK_STATUS";
export const METAMASK_CONNECT_FUNCTION = "METAMASK_CONNECT_FUNCTION";
export const NETWORK_ID = "NETWORK_ID";
export const LOAD = "LOAD";
export const USDT_CONTRACT_INSTANCE = "USDT_CONTRACT_INSTANCE";
